os: linux
dist: trusty
sudo: false
language: python
python:
    - "2.7"
    - "pypy"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
env:
    matrix:
        - TESSERACT=3.04.01-1
        - TESSERACT=3.05.02-3
before_install:
    - export TESSERACT_INSTALL=$HOME/.tesseract
    - export TESSERACT_PKG=$TESSERACT_INSTALL/lib/pkgconfig
    - export LD_LIBRARY_PATH=$TESSERACT_INSTALL/lib:$LD_LIBRARY_PATH
    - export PKG_CONFIG_PATH=$TESSERACT_PKG:$PKG_CONFIG_PATH
    - wget -O - https://github.com/nijel/tesseract-ocr-build/releases/download/$TESSERACT/tesseract.tar.xz | tar -C $HOME -xJf -
install:
    - pip install Cython
    - pip install Pillow
script: python setup.py test
